# Arquivo de workflow para CI/CD da API Lacrei Saúde

name: CI/CD Pipeline para Lacrei Saúde API

on:
  push:
    branches: [ "main" ] # Este workflow só é executado em pushes para a branch 'main'

jobs:
  # --- Job de Testes (CI - Integração Contínua) ---
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v3

      - name: 2. Configurar o Python e Poetry
        uses: actions/setup-python@v3
        with:
          python-version: "3.12" # ATUALIZADO: Versão correta do Python para o projeto
      - uses: snok/install-poetry@v1

      - name: 3. Instalar as dependências
        # ATUALIZADO: Adicionado --no-root para instalar apenas as dependências, não o projeto em si.
        run: poetry install --no-root

      - name: 4. Executar o Lint com Flake8
        run: poetry run flake8 . --ignore=E501,W293,E302,E303

      - name: 5. Executar os testes
        run: |
          export SECRET_KEY='test-secret-key'
          export DEBUG='True'
          poetry run python manage.py test

  # --- Job de Deploy (CD - Entrega Contínua) ---
  deploy:
    # Este job só começa se o job 'build-and-test' for bem-sucedido
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v3

      - name: 2. Configurar as credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: 3. Gerar o ficheiro .zip para deploy
        run: zip -r deploy.zip . -x ".git/*" ".github/*"

      - name: 4. Enviar o pacote para o AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: lacrei-saude-api # O nome da sua aplicação no EB
          environment_name: Lacrei-saude-api-env-2 # O nome do seu ambiente no EB
          region: sa-east-1
          version_label: "v1.2.0-${{ github.sha }}" # Uma etiqueta de versão única
          deployment_package: deploy.zip
